apiVersion: pods.k8s.delta10.nl/v1
kind: PostgresAccess
metadata:
    name: postgresaccesses.access.example.com
spec:
    group: access.example.com
    scope: Namespaced
    names:
        plural: postgresaccesses
        singular: postgresaccess
        kind: PostgresAccess
        shortNames:
            - pgaccess
    versions:
        -   name: v1alpha1
            served: true
            storage: true
            schema:
                openAPIV3Schema:
                    type: object
                    required: [ "spec" ]
                    properties:
                        spec:
                            type: object
                            required: [ "generatedSecret", "grants", "connection" ]
                            properties:
                                generatedSecret:
                                    type: string
                                    minLength: 1

                                # optional; if empty, operator generates and stores in generatedSecret
                                username:
                                    type: string

                                connection:
                                    type: object
                                    description: Connection info OR a reference to an existing standardized secret.
                                    oneOf:
                                        # Option A: point to an existing standardized secret by name, needs to have the required keys (host, port, database, username, password)
                                        -   required: [ "existingSecret" ]
                                            properties:
                                                existingSecret:
                                                    type: string
                                                    minLength: 1

                                        # Option B: provide fields (host/port/db + username/password as string or secretRef)
                                        -   required: [ "host", "port", "database", "username", "password" ]
                                            properties:
                                                host:
                                                    type: string
                                                    minLength: 1
                                                port:
                                                    type: integer
                                                    minimum: 1
                                                    maximum: 65535
                                                database:
                                                    type: string
                                                    minLength: 1

                                                username: # username for connecting to the DB, can be plain or secretRef
                                                    oneOf:
                                                        -   type: string
                                                            minLength: 1
                                                        -   type: object
                                                            required: [ "secretRef" ]
                                                            properties:
                                                                secretRef:
                                                                    type: object
                                                                    required: [ "name", "key" ]
                                                                    properties:
                                                                        name:
                                                                            type: string
                                                                            minLength: 1
                                                                        key:
                                                                            type: string
                                                                            minLength: 1
                                                                    additionalProperties: false
                                                            additionalProperties: false


                                                password: # Password can be provided as plain text or secretRef
                                                    oneOf:
                                                        -   type: string
                                                            minLength: 1
                                                        -   type: object
                                                            required: [ "secretRef" ]
                                                            properties:
                                                                secretRef:
                                                                    type: object
                                                                    required: [ "name", "key" ]
                                                                    properties:
                                                                        name:
                                                                            type: string
                                                                            minLength: 1
                                                                        key:
                                                                            type: string
                                                                            minLength: 1
                                                                    additionalProperties: false
                                                            additionalProperties: false
                                            additionalProperties: false
                                    additionalProperties: false

                                grants:
                                    type: array
                                    minItems: 1
                                    maxItems: 1
                                    items:
                                        type: object
                                        required: [ "database", "privileges" ]
                                        properties:
                                            database:
                                                type: string
                                                minLength: 1
                                            schema:
                                                type: string
                                                default: public
                                                minLength: 1
                                            privileges:
                                                type: array
                                                minItems: 1
                                                items:
                                                    type: string
                                                    enum:
                                                        - SELECT
                                                        - INSERT
                                                        - UPDATE
                                                        - DELETE
                                                        - TRUNCATE
                                                        - REFERENCES
                                                        - TRIGGER
                                                        - CREATE
                                                        - CONNECT
                                                        - TEMPORARY
                                                        - EXECUTE
                                                        - USAGE
                                                        - SET
                                                        - ALTER SYSTEM
                                                        - MAINTAIN
                                        additionalProperties: false

                            additionalProperties: false