## Append samples of your project ##
resources:
  - access_v1_rabbitmqaccess.yaml
  - access_v1_postgresaccess.yaml
  - access_v1_postgresaccess_conn_secret.yaml
  - access_v1_postgresaccess_sec_ref.yaml
  - access_v1_controller.yaml
  - access_v1_redisaccess.yaml
  - access_v1_redisaccess_docker.yaml
  - access_v1_postgresaccess_docker.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
