## Append samples of your project ##
resources:
  - pods_v1_postgresaccess.yaml
  - access_v1_rabbitmqaccess.yaml
  - access_v1_postgresaccess.yaml
  - access_v1_postgresaccess_conn_secret.yaml
  - access_v1_postgresaccess_sec_ref.yaml
  - access_v1_controller.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
